# This is a basic workflow to help you get started with Actions

name: React App Deploy to Surge

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # Runs a single command using the runners shell
    - name: Install NodeJS
      uses: actions/setup-node@v2-beta
      with: 
        version: 12
    # Runs a set of commands using the runners shell
    - name: GitHub Action for Yarn
      uses: Borales/actions-yarn@v2.1.0
      with:
        # Yarn command
        cmd: install # npm install/ yarn install
    
    - name: Build React App
      run: yarn build
    
    - name: install surge  
      run: npm install --global surge
    
    - name: Deploy to Surge
      run: surge ./ build http://bootcamp_material-ui.surge.sh/ --token ${{secrets.SURGE_TOKEN}}
